nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api':
            allow_origin: ['https://middo-frontend-6dn6.vercel.app', 'http://localhost:3000']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            max_age: 3600
