controllers:
    resource: ../src/Controller/
    type: attribute

# Redirection page d'accueil
app_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_dashboard'
        permanent: true
